JUMP(L_append_closure);
L_append_body:
    PUSH(FP);
    MOV(FP,SP);
	PUSH(R1);
	PUSH(R2);
	MOV(R1,FPARG(2));
	MOV(R2,FPARG(3));
	MOV(R3,0);

	MOV(R0,R1);
	CMP(IND(R2),SOB_NIL);
	JUMP_EQ(L_APPEND_EXIT);
	MOV(R0,R2);
	CMP(IND(R1),SOB_NIL);
	JUMP_EQ(L_APPEND_EXIT);

	L_APPEND_LOOP_FOR_THE_CREATION:
	CMP(R1,SOB_NIL);
	JUMP_EQ(L_APPEND_LOOP_FOR_APPENDING);
	PUSH(INDD(R1,1));
	INCR(R3);
	MOV(R1,INDD(R1,2));
	JUMP(L_APPEND_LOOP_FOR_THE_CREATION);

	L_APPEND_LOOP_FOR_APPENDING:
	CMP(R3,IMM(0));
	JUMP_EQ(L_APPEND_DONE);
	PUSH(R2);
	CALL(MAKE_SOB_PAIR);
	DROP(2);
	MOV(R2,R0);
	DECR(R3);
	JUMP(L_APPEND_LOOP_FOR_APPENDING);
	
	L_APPEND_DONE:
	
	MOV(R0,R2);
	L_APPEND_EXIT:
    POP(FP);
    RETURN;


L_error_incorrect_list:
SHOW("ERROR!(CORE-FREE-VARS) numbLALALALALAnt is incorrect",INDD(R2,0));
exit(-1);


L_append_closure:
    PUSH(4);
    CALL(MALLOC);
    DROP(1);
    MOV(INDD(R0,1),IMM(T_CLOSURE));
    MOV(INDD(R0,2),IMM(033311));
    MOV(INDD(R0,3),LABEL(L_append_body));


