JUMP(LEQClos);
LEQBody:
  PUSH(FP);
  MOV(FP, SP);

  CMP(FPARG(1), IMM(2));
  JUMP_NE(L_error_inEQ_not_2_items);

  MOV(R2,FPARG(2));
  MOV(R3,FPARG(3));

  MOV(R4, IND(R2));
  MOV(R5, IND(R3));

  CMP(R4,R5);
  JUMP_NE(EQ_EXIT_FALSE);

EQ_SAME_TYPE:

  CMP(R4, T_INTEGER);
  JUMP_EQ(EQ_INTEGER);

  CMP(R4, T_CHAR);
  JUMP_EQ(EQ_CHAR);

  
  CMP(R4, T_VOID);
  JUMP_EQ(EQ_EXIT_TRUE);

  CMP(R4, T_BOOL);
  JUMP_EQ(EQ_BOOL);
  
  CMP(R4, T_VECTOR);
  JUMP_EQ(EQ_VECTOR);
  
  CMP(R4, T_SYMBOL);
  JUMP_EQ(EQ_SYMBOL);
  

EQ_STRING:

  MOV(R1,FPARG(2));
  MOV(R2,FPARG(3));
  CMP(R1,R2);
  JUMP_NE(EQ_EXIT_FALSE);
  JUMP(EQ_EXIT_TRUE);

EQ_SYMBOL:
    MOV(R1,FPARG(2));
    MOV(R2,FPARG(3));
    
    MOV(R1,INDD(R1,1));
    MOV(R2,INDD(R2,1));
	MOV(R4,INDD(R1,1));
	MOV(R5,INDD(R2,1));
    CMP(R4,R5);
    JUMP_NE(EQ_EXIT_FALSE);
    MOV(R3,INDD(R1,1));
    ADD(R3,IMM(2));
EQ_SYMBOL_LOOP:

    CMP(R3,IMM(2));
    JUMP_EQ(EQ_EXIT_TRUE);
    DECR(R3);
	MOV(R4,INDD(R1,R3));
	MOV(R5,INDD(R2,R3));
    CMP(R4,R5);
    JUMP_NE(EQ_EXIT_FALSE);
	JUMP(EQ_SYMBOL_LOOP);
    


EQ_VECTOR:

 MOV(R5,INDD(FPARG(2),1));
 MOV(R6,INDD(FPARG(3),1));
 CMP(R5,R6);
 JUMP_NE(EQ_EXIT_FALSE);
 MOV(R2,INDD(FPARG(2),2));
 MOV(R3,INDD(FPARG(3),2));
 
EQ_VECTOR_LOOP:
  CMP(R2,R3);
  JUMP_NE(EQ_EXIT_FALSE);
  INCR(R2);
  INCR(R3);
  DECR(R5);
  CMP(R5,0);
  JUMP_EQ(EQ_EXIT_TRUE);
  JUMP(EQ_VECTOR_LOOP);
  
EQ_BOOL:

  MOV(R1,INDD(FPARG(2),1));
  MOV(R2,INDD(FPARG(3),1));

  CMP(R1,R2);
  JUMP_NE(EQ_EXIT_FALSE);
  JUMP(EQ_EXIT_TRUE);

  
EQ_INTEGER:

  MOV(R1,INDD(FPARG(2),1));
  MOV(R2,INDD(FPARG(2),2));

  MOV(R5,INDD(FPARG(3),1));
  MOV(R6,INDD(FPARG(3),2));

  CMP(R1,R5);
  JUMP_NE(EQ_EXIT_FALSE);
  CMP(R2,R6);
  JUMP_NE(EQ_EXIT_FALSE);
  JUMP(EQ_EXIT_TRUE);

EQ_CHAR:

  MOV(R1,INDD(FPARG(2),1));
  MOV(R2,INDD(FPARG(3),1));

  CMP(R1,R2);
  JUMP_NE(EQ_EXIT_FALSE);
  JUMP(EQ_EXIT_TRUE);


EQ_EXIT_FALSE:
  MOV(R0, SOB_FALSE);
  POP(FP);
  RETURN;

EQ_EXIT_TRUE:
  MOV(R0, SOB_TRUE);
  POP(FP);
  RETURN;


L_error_inEQ_not_2_items:
	INFO;
	SHOW("ERROR! did'nt get two arguments to eq?",FPARG(1));    
LEQClos:
    PUSH(4);
    CALL(MALLOC);
    DROP(1);
    MOV(INDD(R0,1),IMM(T_CLOSURE));
    MOV(INDD(R0,2),IMM(022230));
    MOV(INDD(R0,3),LABEL(LEQBody));
